2025-03-26 13:22:01,707 INFO parser_task.py::parse:L43 :  DataFile parsing started for file None
2025-03-26 13:22:01,935 INFO decoders.py::get_suggested_decoder:L202 :  Returning CSV decoder with a confidence score of 1.0
2025-03-26 13:22:01,941 INFO row_schema.py::parse_and_validate:L298 :  1 category4 preparser error(s) encountered.
2025-03-26 13:22:01,945 DEBUG fra_parser.py::parse_and_validate:L71 :  Record #0 from line 1 is invalid.
2025-03-26 13:22:01,946 INFO util.py::remove_case_due_to_errors:L351 :  Case consistency errors generated, removing case from in memory cache. Record(s) info: [('TE1', None, None)].
2025-03-26 13:22:01,946 INFO row_schema.py::parse_and_validate:L298 :  1 category4 preparser error(s) encountered.
2025-03-26 13:22:01,946 DEBUG fra_parser.py::parse_and_validate:L71 :  Record #0 from line 2 is invalid.
2025-03-26 13:22:01,947 INFO util.py::remove_case_due_to_errors:L351 :  Case consistency errors generated, removing case from in memory cache. Record(s) info: [('TE1', None, None)].
2025-03-26 13:22:01,947 INFO row_schema.py::parse_and_validate:L298 :  1 category4 preparser error(s) encountered.
2025-03-26 13:22:01,948 DEBUG fra_parser.py::parse_and_validate:L71 :  Record #0 from line 3 is invalid.
2025-03-26 13:22:01,948 INFO util.py::remove_case_due_to_errors:L351 :  Case consistency errors generated, removing case from in memory cache. Record(s) info: [('TE1', None, None)].
2025-03-26 13:22:01,948 INFO row_schema.py::parse_and_validate:L298 :  1 category4 preparser error(s) encountered.
2025-03-26 13:22:01,949 DEBUG fra_parser.py::parse_and_validate:L71 :  Record #0 from line 4 is invalid.
2025-03-26 13:22:01,949 INFO util.py::remove_case_due_to_errors:L351 :  Case consistency errors generated, removing case from in memory cache. Record(s) info: [('TE1', None, None)].
2025-03-26 13:22:01,949 INFO row_schema.py::parse_and_validate:L298 :  1 category4 preparser error(s) encountered.
2025-03-26 13:22:01,950 DEBUG fra_parser.py::parse_and_validate:L71 :  Record #0 from line 5 is invalid.
2025-03-26 13:22:01,950 INFO util.py::remove_case_due_to_errors:L351 :  Case consistency errors generated, removing case from in memory cache. Record(s) info: [('TE1', None, None)].
2025-03-26 13:22:01,951 INFO row_schema.py::parse_and_validate:L298 :  1 category4 preparser error(s) encountered.
2025-03-26 13:22:01,951 DEBUG fra_parser.py::parse_and_validate:L71 :  Record #0 from line 6 is invalid.
2025-03-26 13:22:01,951 INFO util.py::remove_case_due_to_errors:L351 :  Case consistency errors generated, removing case from in memory cache. Record(s) info: [('TE1', None, None)].
2025-03-26 13:22:01,951 INFO row_schema.py::parse_and_validate:L298 :  1 category4 preparser error(s) encountered.
2025-03-26 13:22:01,952 DEBUG fra_parser.py::parse_and_validate:L71 :  Record #0 from line 7 is invalid.
2025-03-26 13:22:01,952 INFO util.py::add_record:L302 :  Record's case has already been removed due to category four errors. Not adding record with info: (TE1, None)
2025-03-26 13:22:01,953 INFO row_schema.py::parse_and_validate:L298 :  1 category4 preparser error(s) encountered.
2025-03-26 13:22:01,954 DEBUG fra_parser.py::parse_and_validate:L71 :  Record #0 from line 10 is invalid.
2025-03-26 13:22:01,954 INFO util.py::remove_case_due_to_errors:L351 :  Case consistency errors generated, removing case from in memory cache. Record(s) info: [('TE1', None, None)].
2025-03-26 13:22:01,955 INFO row_schema.py::parse_and_validate:L298 :  1 category4 preparser error(s) encountered.
2025-03-26 13:22:01,956 DEBUG fra_parser.py::parse_and_validate:L71 :  Record #0 from line 11 is invalid.
2025-03-26 13:22:01,956 INFO util.py::remove_case_due_to_errors:L351 :  Case consistency errors generated, removing case from in memory cache. Record(s) info: [('TE1', None, None)].
2025-03-26 13:22:01,957 INFO row_schema.py::parse_and_validate:L298 :  1 category4 preparser error(s) encountered.
2025-03-26 13:22:01,957 DEBUG fra_parser.py::parse_and_validate:L71 :  Record #0 from line 12 is invalid.
2025-03-26 13:22:01,958 INFO util.py::remove_case_due_to_errors:L351 :  Case consistency errors generated, removing case from in memory cache. Record(s) info: [('TE1', None, None)].
2025-03-26 13:22:01,958 INFO row_schema.py::parse_and_validate:L298 :  1 category4 preparser error(s) encountered.
2025-03-26 13:22:01,958 DEBUG fra_parser.py::parse_and_validate:L71 :  Record #0 from line 13 is invalid.
2025-03-26 13:22:01,959 INFO util.py::remove_case_due_to_errors:L351 :  Case consistency errors generated, removing case from in memory cache. Record(s) info: [('TE1', None, None)].
2025-03-26 13:22:01,959 DEBUG base_parser.py::bulk_create_records:L54 :  Bulk creating records.
2025-03-26 13:22:01,959 INFO base_parser.py::bulk_create_records:L80 :  Created 0/0 records.
2025-03-26 13:22:01,960 DEBUG base_parser.py::bulk_create_errors:L89 :  Bulk creating ParserErrors.
2025-03-26 13:22:01,969 INFO base_parser.py::bulk_create_errors:L92 :  Created 24/24 ParserErrors.
2025-03-26 13:22:01,984 INFO parser_task.py::parse:L68 :  Parsing finished for file -> {id: 117, filename: fra.csv, STT: Arkansas (05), S3 location: data_files/2021/Q1/4/Work Outcomes of TANF Exiters/fra.csv} with status Rejected.
2025-03-26 13:22:02,039 INFO parser_task.py::parse:L117 :  DataFile parsing finished for file None
